[package]
name = "safe"
version = "0.1.0"
authors = ["Michael Bryan <michaelfbryan@gmail.com>", "Mazdak Farrokhzad <twingoow@gmail.com>"]
edition = "2018"
description = "A `#[safe]` attribute for explaining why `unsafe { ... }` is OK."

[dependencies]

[lib]
proc-macro = true